export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CURRENT = 'CURRENT'
export const FAIL = 'FAIL'
export const HANDLEGRANTED = 'HANDLEGRANTED'
export const UPDATEUSER = 'UPDATEUSER'
